spring:
  application:
    name: api-agrotis
  profiles:
    active: dev
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:mem:agrotis-db
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-ui
server:
  port: 8080
  cors: false
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-exception: 'false'
    include-binding-errors: always
    include-message: always